sudo: false
language: python

python:
  - "3.4"
  - "3.6"

install: pip -q install tox codacy-coverage codecov

script:
  - tox -e cover

after_success:
  - python-codacy-coverage -r coverage.xml
  - codecov
