environment:
  PYTHON: "C:\\Python34"

install:
  - ps: "ls \"C:/\""
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "pip install tox"

build: false

test_script:
  - "python -m tox -e py33,py34,py35"
