environment:
  matrix:
  - PYTHON: "C:\\Python36"
  - PYTHON: "C:\\Python36-x64"
  CODECOV_TOKEN: f67nOyITJWX7wE2ASpCKz/JOXLd89y5YnDdwmQW+Fs3DEVUBN47DjpKQN3QT0L2G

install:
  - "%PYTHON%\\python.exe -m pip -q install tox wheel codecov"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox -e cover"

after_test:
  - "%PYTHON%\\python.exe setup.py -q sdist bdist_wheel bdist_msi bdist_wininst"
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junit.xml))
  - "%PYTHON%\\python.exe -m codecov"

artifacts:
  - path: dist\*
