environment:
  matrix:
  - PYTHON: "C:\\Python35"
  - PYTHON: "C:\\Python35-x64"

install:
  - "%PYTHON%\\python.exe -m pip install tox wheel"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox -e py33,py34,py35,ut"

after_test:
  - "%PYTHON%\\python.exe setup.py -q sdist bdist_wheel bdist_msi bdist_wininst"

artifacts:
  - path: dist\*
