init:
  - set PATH=C:\Python36-x64;C:\Python36-x64\Scripts;%PATH%

build: off

install:
  - pip install tox wheel
  - python -c "import sys,platform; print(sys.platform); print(platform.machine())"

test_script:
  - tox -e cover

