init:
  - set PATH=c:\Python36-x64;C:\Python36-x64\Scripts;%PATH%

install:
  - pip -q install tox wheel
  - python -c "import sys,platform; print(sys.platform); print(platform.machine())"

build: off

test_script:
  - tox -e cover

after_test:
  - python setup.py -q sdist bdist_wheel bdist_msi bdist_wininst

artifacts:
  - path: dist\*

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/5e1bcd4a381ee027f33e
    on_build_failure: true
    on_build_status_changed: true

